#! /bin/bash

function __date_segment
{
	local __local_date_icon="$(convertToUTF8 "${__date_icon}" "${__date_icon_width}")"

        [[ "${1}" == "fg" ]] && {
                echo "${__date_foreground}"
                return
        }
        [[ "${1}" == "bg" ]] && {
                echo "${__date_background}"
                return
        }

        __print_colors "${__local_date_icon} ${__date_format}" "${__date_foreground}" "${__date_background}"
}
