#! /bin/bash

function __home_segment
{
	local __home_dir_type='local'
	local __nfs_icon=''
	local __dev_icon=''
	local __nfs_icon_width=1
	local __dev_icon_width=1

        [[ "${1}" == "fg" ]] && {
                echo "${__home_foreground}"
                return
        }
        [[ "${1}" == "bg" ]] && {
                echo "${__home_background}"
                return
        }

	[[ -n "${__home_nfs_icon}" ]] && { __nfs_icon=${__home_nfs_icon}; __nfs_icon_width=${__home_nfs_icon_width:-1}; }
	[[ -n "${__home_dev_icon}" ]] && { __dev_icon=${__home_dev_icon}; __dev_icon_width=${__home_dev_icon_width:-1}; }

	__home_dir_type=$(df -kP ~ |
		sed -ne '/Filesystem/d' \
		    -e '/dev/{ s;^.*$;dev;; h; }' \
		    -e '/^[^:]*:/{ s;^.*$;nfs;; h; }' \
		    -e '${ x; p; }')

	[[ ${__home_dir_type} == "nfs" ]] && __home_dir_type="$(convertToUTF8 "${__nfs_icon}" "${__nfs_icon_width}")"
	[[ ${__home_dir_type} == "dev" ]] && __home_dir_type="$(convertToUTF8 "${__dev_icon}" "${__dev_icon_width}")"

	__print_colors "$(convertToUTF8 "${__home_icon}" "${__home_icon_width}") ${__home_dir_type}" "${__home_foreground}" "${__home_background}"
}
