#! /bin/bash

__jboss_product=''

function __jboss_setup
{
	# $ rpm -q eap7-wildfly
	# eap7-wildfly-7.3.5-2.GA_redhat_00001.1.el8eap.noarch
	__jboss_product=$(rpm -q eap7-wildfly 2> /dev/null | sed -ne 's;^eap7-wildfly-\([0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}\)-.*$;\1;p')
}

function __jboss_segment
{
	[[ -n "${__jboss_product}" ]] && {
        	[[ "${1}" == "fg" ]] && {
                	echo "${__jboss_foreground}"
                	return
        	}
        	[[ "${1}" == "bg" ]] && {
                	echo "${__jboss_background}"
                	return
        	}

		__print_colors "$(convertToUTF8 "${__jboss_icon}" "${__jboss_icon_width}") ${__jboss_product}" \
			"${__jboss_foreground}" "${__jboss_background}"
	}
}

__jboss_setup

unset -f __jboss_setup
