#! /bin/bash

function __pwd_segment
{
	# there is always a current working directory, no need
	# to verify if there is one...
        [[ "${1}" == "fg" ]] && {
                echo "${__pwd_foreground}"
                return
        }
        [[ "${1}" == "bg" ]] && {
                echo "${__pwd_background}"
                return
        }

	__print_colors "$(convertToUTF8 "${__pwd_icon}" "${__pwd_icon_width}") ${__pwd_format}" "${__pwd_foreground}" "${__pwd_background}"
}
